### ISSUE TITLE
(FEATURE TARGET) perfect the synchronization

### ISSUE THREAD

**Issue by mcmonkey4eva** [mcmonkeyprojects/DenizenModels#11]
DModels at its heart works by spawning armor stands with items on their heads and moving them around.

This uses two core pieces: teleporting the location, and adjusting the `armor_pose`.

When armor_pose is updated, it is instant - the model snaps to the new rotation.
When location is updated, this is delayed - the client does a slow lerp to its target location.

The end result of this is that animations that both rotate and move at the same time visibly bend and distort as the position and rotation lose sync with each other.

This feature target is an open request for any contributors to help find a way to get both of these updates in sync.
Either by making both instant, or making both slow-lerp.

-----

An idea that came up a while ago (initially on Discord by calicokid) that we could potentially:
A: rapidly despawn&spawn new armor stands to cause an instant position update, rather than moving the same stands.
Or B: spawn *two* stands for every model piece, and have one visible and the other invisible, and move the invisible ones ahead and make them visible on the next frame (to implement the "visible" or not part, probably could equip/unequip the item from the entity's head)

**Comment by FutureMaximus** [comment]
Sync is now perfect.
